/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuizeApp.gui;

import QuizApp.Dao.QuestionDao;
import QuizApp.pojo.QuestionPojo;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Smart computer
 */
//file:/E:/sunil payslip/2xx.jpg
public class AttemptQuizFrame extends javax.swing.JFrame {

    /**
     * Creates new form AttemptQuizFrame
     */
    private List<QuestionPojo> questions=null;
    QuestionPojo q1=null;
    int score=0;
    boolean f5050=false,f2x=false,lifeline=false,f=false;
    public AttemptQuizFrame() {
        initComponents();
        this.setTitle("AttemptQuizFrame");
        this.setLocationRelativeTo(null);
        loadQuetions();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        txtque = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        o1 = new javax.swing.JRadioButton();
        o2 = new javax.swing.JRadioButton();
        o3 = new javax.swing.JRadioButton();
        o4 = new javax.swing.JRadioButton();
        submit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn2X = new javax.swing.JButton();
        submit2 = new javax.swing.JButton();
        btn5050 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(102, 50, 90));

        txtque.setBackground(new java.awt.Color(0, 0, 0));
        txtque.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtque.setForeground(new java.awt.Color(255, 255, 255));
        txtque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtqueActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("QUIZ QUESTIONS");

        o1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(o1);
        o1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        o1.setForeground(new java.awt.Color(255, 255, 255));
        o1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o1ActionPerformed(evt);
            }
        });

        o2.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(o2);
        o2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        o2.setForeground(new java.awt.Color(255, 255, 255));
        o2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o2ActionPerformed(evt);
            }
        });

        o3.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(o3);
        o3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        o3.setForeground(new java.awt.Color(255, 255, 255));

        o4.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(o4);
        o4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        o4.setForeground(new java.awt.Color(255, 255, 255));

        submit.setBackground(new java.awt.Color(153, 0, 153));
        submit.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\sunil payslip\\QT.png")); // NOI18N

        btn2X.setBackground(new java.awt.Color(255, 255, 255));
        btn2X.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        btn2X.setText("2X Two Attemp");
        btn2X.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2XActionPerformed(evt);
            }
        });

        submit2.setBackground(new java.awt.Color(153, 0, 153));
        submit2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        submit2.setText("Back");
        submit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit2ActionPerformed(evt);
            }
        });

        btn5050.setBackground(new java.awt.Color(255, 255, 255));
        btn5050.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        btn5050.setText("50-50 Two Wrong Option eliminate");
        btn5050.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5050ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(txtque, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(o3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(o4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(o2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(o1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btn5050, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(btn2X, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)))
                .addGap(0, 31, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(submit2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(txtque, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(o1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(o2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(o3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(o4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(submit2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn2X, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5050, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void o2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_o2ActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        if(o1.isSelected()){
            if(o1.getText().trim().equals(q1.getAnswer())){
                score++;
                JOptionPane.showMessageDialog(null,"righte Answer");
                
                showQuestions();
               
            }else{
                 JOptionPane.showMessageDialog(null,"Wrong Answer");
                 if(f2x){
                     JOptionPane.showMessageDialog(null,"You Can Attempt ones again");
                     f2x=false;
                 }
                  return;
                }
        }else if(o2.isSelected()){
            if(o2.getText().trim().equals(q1.getAnswer())){
                score++;
                JOptionPane.showMessageDialog(null,"righte Answer");
                
                showQuestions();
                
            }else{
                JOptionPane.showMessageDialog(null,"Wrong Answer");
                if(f2x){
                     JOptionPane.showMessageDialog(null,"You Can Attempt ones again");
                     f2x=false;
                 }
                  return;
            }
        }else if(o3.isSelected()){
            if(o3.getText().trim().equals(q1.getAnswer())){
                score++;
                JOptionPane.showMessageDialog(null,"righte Answer");
                
                showQuestions();
                
            }else{
                JOptionPane.showMessageDialog(null,"Wrong Answer");
                if(f2x){
                     JOptionPane.showMessageDialog(null,"You Can Attempt ones again");
                     f2x=false;
                 }
                  return;
            }
        }else if(o4.isSelected()){
            if(o4.getText().trim().equals(q1.getAnswer())){
                score++;
                JOptionPane.showMessageDialog(null,"righte Answer");
               
                showQuestions();
                
            }else{
                JOptionPane.showMessageDialog(null,"Wrong Answer");
                if(f2x){
                     JOptionPane.showMessageDialog(null,"You Can Attempt ones again");
                     f2x=false;
                 }
                  return;
            }
        }else {
            JOptionPane.showMessageDialog(null,"Select an Option First");
            return;
        }
        
    }//GEN-LAST:event_submitActionPerformed

    private void o1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_o1ActionPerformed

    private void txtqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtqueActionPerformed

    private void btn2XActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2XActionPerformed
        // TODO add your handling code here:
        if(lifeline){
            JOptionPane.showMessageDialog(null," You Cannot Use Two LifeLine At One Time!");
            return;
        }
        if(f){
            JOptionPane.showMessageDialog(null,"You Can Use Life Line At One Time Only!");
            return;
        }
        f=true;
        lifeline=true;
        f2x=true;
    }//GEN-LAST:event_btn2XActionPerformed

    private void submit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_submit2ActionPerformed

    private void btn5050ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5050ActionPerformed
        // TODO add your handling code here:
        if(lifeline){
            JOptionPane.showMessageDialog(null," You Cannot Use Two LifeLine At One Time!");
            return;
        }
        if(f5050){
            JOptionPane.showMessageDialog(null,"You Can Use Life Line At One Time Only!");
            return;
        }
        String ans=q1.getAnswer();
        if(ans.equals(o1.getText())){
            o2.setVisible(false);
            o3.setVisible(false);
        }else if(ans.equals(o2.getText())){
            o1.setVisible(false);
            o3.setVisible(false);
        }else if(ans.equals(o3.getText())){
            o2.setVisible(false);
            o1.setVisible(false);
        }else if(ans.equals(o4.getText())){
            o1.setVisible(false);
            o3.setVisible(false);
        }
        lifeline=true;
        f5050=true;
    }//GEN-LAST:event_btn5050ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AttemptQuizFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AttemptQuizFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AttemptQuizFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AttemptQuizFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AttemptQuizFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn2X;
    private javax.swing.JButton btn5050;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton o1;
    private javax.swing.JRadioButton o2;
    private javax.swing.JRadioButton o3;
    private javax.swing.JRadioButton o4;
    private javax.swing.JButton submit;
    private javax.swing.JButton submit2;
    private javax.swing.JTextField txtque;
    // End of variables declaration//GEN-END:variables

    private void loadQuetions() {
        try{
             questions=QuestionDao.getAllQuestions("ACTIVE");
             q1=questions.get(0);
             int i=q1.getQuestionId()+1;
             
             txtque.setText(q1.getQuestion());
             o1.setText(q1.getOption1());
             o2.setText(q1.getOption2());
             o3.setText(q1.getOption3());
             o4.setText(q1.getOption4());
             questions.remove(0);
             if(questions.isEmpty()){
                  JOptionPane.showMessageDialog(null,"Attempted All Quetions");
                  return;
             }
        }catch(SQLException sq){
            JOptionPane.showMessageDialog(null,"DB Error in Attempt quiz");
            return;
        }
    }
    
    private void showQuestions() {
        if(questions.isEmpty()){
                  JOptionPane.showMessageDialog(null,"Attempted All Quetions");
                  
                  return;
             }
        if(lifeline)lifeline=false;
             o1.setVisible(true);
             o2.setVisible(true);
             o3.setVisible(true);
             o4.setVisible(true);
             o1.setFocusable(false);
             o2.setFocusable(false);
             o3.setFocusable(false);
             o4.setFocusable(false);
             q1=questions.get(0);
             int i=q1.getQuestionId()+1;
             
             txtque.setText(q1.getQuestion());
             o1.setText(q1.getOption1());
             o2.setText(q1.getOption2());
             o3.setText(q1.getOption3());
             o4.setText(q1.getOption4());
             questions.remove(0);
    }

    
}
