/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package in.scalive.Gui.Swingbuilder;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.Date;
import javax.swing.ImageIcon;

/**
 *
 * @author DELL
 */
public class MyJFrame2 extends javax.swing.JFrame {

    /**
     * Creates new form MyJframe2 
     */
    public MyJFrame2() {
        initComponents();
//        setTitle("my jFrame");
//          Container ct = getContentpane();
//         ct.setBackground(Color.yellow);
//           myJPanel.setBackground(Color.yellow);
           setLocationRelativeTo(null);
//           Toolkit tk = Toolkit.getDefaultToolkit();
//           Image img = tk.getImage("D:\\Gurjar\\Html\\media\\images\\ALLOW.GIF");
//           setIconImage(img);
           
           ImageIcon icon = new ImageIcon("D:\\Gurjar\\Html\\media\\images\\ALLOW.GIF");
           btnChangeColor.setIcon(icon);
           
            btnChangeColor.setToolTipText("click me for changing color");
            
               

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblGreetings = new javax.swing.JLabel();
        MyPanel = new javax.swing.JPanel();
        btnChangeColor = new javax.swing.JButton();
        btnQuit = new javax.swing.JButton();
        btnShowTimeStamp = new javax.swing.JButton();
        lblShowTimeStamp = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        btnGreet = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        lblGreeting = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        lblGreetings.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnChangeColor.setBackground(new java.awt.Color(255, 153, 51));
        btnChangeColor.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        btnChangeColor.setText("Change Color");
        btnChangeColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeColorActionPerformed(evt);
            }
        });

        btnQuit.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnQuit.setText("Quit");
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });

        btnShowTimeStamp.setFont(new java.awt.Font("Segoe Print", 1, 20)); // NOI18N
        btnShowTimeStamp.setText("Show TimeStamp");
        btnShowTimeStamp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowTimeStampActionPerformed(evt);
            }
        });

        lblShowTimeStamp.setBackground(new java.awt.Color(102, 255, 51));
        lblShowTimeStamp.setFont(new java.awt.Font("Wide Latin", 1, 18)); // NOI18N
        lblShowTimeStamp.setForeground(new java.awt.Color(255, 51, 255));
        lblShowTimeStamp.setOpaque(true);

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Gurjar\\Html\\media\\images\\ALLOW.GIF")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        jLabel2.setText("Enter your name");

        jLabel3.setFont(new java.awt.Font("Wide Latin", 1, 18)); // NOI18N
        jLabel3.setText("Greeting App");

        txtUserName.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N

        btnGreet.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnGreet.setText("Greet");
        btnGreet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGreetActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnExit.setText("Quit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        lblGreeting.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\OneDrive\\Pictures\\kheloindia.jpg")); // NOI18N

        javax.swing.GroupLayout MyPanelLayout = new javax.swing.GroupLayout(MyPanel);
        MyPanel.setLayout(MyPanelLayout);
        MyPanelLayout.setHorizontalGroup(
            MyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MyPanelLayout.createSequentialGroup()
                .addGroup(MyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MyPanelLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MyPanelLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(lblShowTimeStamp, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MyPanelLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(MyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(MyPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(52, 52, 52)
                                    .addComponent(txtUserName))
                                .addGroup(MyPanelLayout.createSequentialGroup()
                                    .addComponent(btnChangeColor)
                                    .addGap(78, 78, 78)
                                    .addComponent(btnQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(86, 86, 86)
                                    .addComponent(btnShowTimeStamp))
                                .addGroup(MyPanelLayout.createSequentialGroup()
                                    .addGap(216, 216, 216)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(MyPanelLayout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(lblGreeting, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(MyPanelLayout.createSequentialGroup()
                                .addComponent(btnGreet)
                                .addGap(129, 129, 129)
                                .addComponent(btnExit)
                                .addGap(43, 43, 43)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        MyPanelLayout.setVerticalGroup(
            MyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MyPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lblShowTimeStamp, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(MyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChangeColor, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnShowTimeStamp, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(MyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(lblGreeting, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(MyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MyPanelLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(btnExit))
                    .addGroup(MyPanelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btnGreet))
                    .addGroup(MyPanelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(94, 94, 94))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 770, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChangeColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeColorActionPerformed
        // TODO add your handling code here:
        MyPanel.setBackground(Color.red);
    }//GEN-LAST:event_btnChangeColorActionPerformed

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnQuitActionPerformed

    private void btnShowTimeStampActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowTimeStampActionPerformed
        // TODO add your handling code here:
        Date today=new Date();
//        lblShowTimeStamp.setText(today+"");
          lblShowTimeStamp.setText(today.toString());
    }//GEN-LAST:event_btnShowTimeStampActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnGreetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGreetActionPerformed
        // TODO add your handling code here:
        String name = txtUserName.getText();
        lblGreeting.setText("Good Evening "+name);
    }//GEN-LAST:event_btnGreetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyJFrame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MyPanel;
    private javax.swing.JButton btnChangeColor;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnGreet;
    private javax.swing.JButton btnQuit;
    private javax.swing.JButton btnShowTimeStamp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblGreeting;
    private javax.swing.JLabel lblGreetings;
    private javax.swing.JLabel lblShowTimeStamp;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
